---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 08/02/2021 10:21
---
local json = require("json")

GROUP = {
    ClassName = "GROUP",
}


--- Enumerator for location at airbases
-- @type GROUP.Takeoff
GROUP.Takeoff = {
    Air = 1,
    Runway = 2,
    Hot = 3,
    Cold = 4,
}


AI_A2A_DISPATCHER = {
    ClassName = "AI_A2A_DISPATCHER",
    Detection = nil,
}


--- Squadron data structure.
-- @type AI_A2A_DISPATCHER.Squadron
-- @field #string Name Name of the squadron.
-- @field #number ResourceCount Number of resources.
-- @field #string AirbaseName Name of the home airbase.
-- @field Wrapper.Airbase#AIRBASE Airbase The home airbase of the squadron.
-- @field #boolean Captured If true, airbase of the squadron was captured.
-- @field #table Resources Flight group resources Resources[TemplateID][GroupName] = SpawnGroup.
-- @field #boolean Uncontrolled If true, flight groups are spawned uncontrolled and later activated.
-- @field #table Gci GCI.
-- @field #number Overhead Squadron overhead.
-- @field #number Grouping Squadron flight group size.
-- @field #number Takeoff Takeoff type.
-- @field #number TakeoffAltitude Altitude in meters for spawn in air.
-- @field #number Landing Landing type.
-- @field #number FuelThreshold Fuel threshold [0,1] for RTB.
-- @field #string TankerName Name of the refuelling tanker.
-- @field #table Table of template group names of the squadron.
-- @field #table Spawn Table of spaws Core.Spawn#SPAWN.
-- @field #table TemplatePrefixes
-- @field #boolean Racetrack If true, CAP flights will perform a racetrack pattern rather than randomly patrolling the zone.
-- @field #number RacetrackLengthMin Min Length of race track in meters. Default 10,000 m.
-- @field #number RacetrackLengthMax Max Length of race track in meters. Default 15,000 m.
-- @field #number RacetrackHeadingMin Min heading of race track in degrees. Default 0 deg, i.e. from South to North.
-- @field #number RacetrackHeadingMax Max heading of race track in degrees. Default 180 deg, i.e. from North to South.
-- @field #number RacetrackDurationMin Min duration in seconds before the CAP flight changes its orbit position. Default never.
-- @field #number RacetrackDurationMax Max duration in seconds before the CAP flight changes its orbit position. Default never.

--- Enumerator for spawns at airbases
-- @type AI_A2A_DISPATCHER.Takeoff
-- @extends Wrapper.Group#GROUP.Takeoff

--- @field #AI_A2A_DISPATCHER.Takeoff Takeoff
AI_A2A_DISPATCHER.Takeoff = GROUP.Takeoff

--- Defnes Landing location.
-- @field Landing
AI_A2A_DISPATCHER.Landing = {
    NearAirbase = 1,
    AtRunway = 2,
    AtEngineShutdown = 3,
}

CALLSIGN={
    -- Aircraft
    Aircraft={
        Enfield=1,
        Springfield=2,
        Uzi=3,
        Colt=4,
        Dodge=5,
        Ford=6,
        Chevy=7,
        Pontiac=8,
        -- A-10A or A-10C
        Hawg=9,
        Boar=10,
        Pig=11,
        Tusk=12,
    },
    -- AWACS
    AWACS={
        Overlord=1,
        Magic=2,
        Wizard=3,
        Focus=4,
        Darkstar=5,
    },
    -- Tanker
    Tanker={
        Texaco=1,
        Arco=2,
        Shell=3,
    },
    -- JTAC
    JTAC={
        Axeman=1,
        Darknight=2,
        Warrier=3,
        Pointer=4,
        Eyeball=5,
        Moonbeam=6,
        Whiplash=7,
        Finger=8,
        Pinpoint=9,
        Ferret=10,
        Shaba=11,
        Playboy=12,
        Hammer=13,
        Jaguar=14,
        Deathstar=15,
        Anvil=16,
        Firefly=17,
        Mantis=18,
        Badger=19,
    },
    -- FARP
    FARP={
        London=1,
        Dallas=2,
        Paris=3,
        Moscow=4,
        Berlin=5,
        Rome=6,
        Madrid=7,
        Warsaw=8,
        Dublin=9,
        Perth=10,
    },
} --#CALLSIGN

AIRBOSS = {}
AIRBOSS.Difficulty = {
    EASY="Flight Student",
    NORMAL="Naval Aviator",
    HARD="TOPGUN Graduate",
}
AIRBASE = {
}

--- Enumeration to identify the airbases in the Caucasus region.
--
-- These are all airbases of Caucasus:
--
--   * AIRBASE.Caucasus.Gelendzhik
--   * AIRBASE.Caucasus.Krasnodar_Pashkovsky
--   * AIRBASE.Caucasus.Sukhumi_Babushara
--   * AIRBASE.Caucasus.Gudauta
--   * AIRBASE.Caucasus.Batumi
--   * AIRBASE.Caucasus.Senaki_Kolkhi
--   * AIRBASE.Caucasus.Kobuleti
--   * AIRBASE.Caucasus.Kutaisi
--   * AIRBASE.Caucasus.Tbilisi_Lochini
--   * AIRBASE.Caucasus.Soganlug
--   * AIRBASE.Caucasus.Vaziani
--   * AIRBASE.Caucasus.Anapa_Vityazevo
--   * AIRBASE.Caucasus.Krasnodar_Center
--   * AIRBASE.Caucasus.Novorossiysk
--   * AIRBASE.Caucasus.Krymsk
--   * AIRBASE.Caucasus.Maykop_Khanskaya
--   * AIRBASE.Caucasus.Sochi_Adler
--   * AIRBASE.Caucasus.Mineralnye_Vody
--   * AIRBASE.Caucasus.Nalchik
--   * AIRBASE.Caucasus.Mozdok
--   * AIRBASE.Caucasus.Beslan
--
-- @field Caucasus
AIRBASE.Caucasus = {
    ["Gelendzhik"] = "Gelendzhik",
    ["Krasnodar_Pashkovsky"] = "Krasnodar-Pashkovsky",
    ["Sukhumi_Babushara"] = "Sukhumi-Babushara",
    ["Gudauta"] = "Gudauta",
    ["Batumi"] = "Batumi",
    ["Senaki_Kolkhi"] = "Senaki-Kolkhi",
    ["Kobuleti"] = "Kobuleti",
    ["Kutaisi"] = "Kutaisi",
    ["Tbilisi_Lochini"] = "Tbilisi-Lochini",
    ["Soganlug"] = "Soganlug",
    ["Vaziani"] = "Vaziani",
    ["Anapa_Vityazevo"] = "Anapa-Vityazevo",
    ["Krasnodar_Center"] = "Krasnodar-Center",
    ["Novorossiysk"] = "Novorossiysk",
    ["Krymsk"] = "Krymsk",
    ["Maykop_Khanskaya"] = "Maykop-Khanskaya",
    ["Sochi_Adler"] = "Sochi-Adler",
    ["Mineralnye_Vody"] = "Mineralnye Vody",
    ["Nalchik"] = "Nalchik",
    ["Mozdok"] = "Mozdok",
    ["Beslan"] = "Beslan",
}

--- These are all airbases of Nevada:
--
--   * AIRBASE.Nevada.Creech_AFB
--   * AIRBASE.Nevada.Groom_Lake_AFB
--   * AIRBASE.Nevada.McCarran_International_Airport
--   * AIRBASE.Nevada.Nellis_AFB
--   * AIRBASE.Nevada.Beatty_Airport
--   * AIRBASE.Nevada.Boulder_City_Airport
--   * AIRBASE.Nevada.Echo_Bay
--   * AIRBASE.Nevada.Henderson_Executive_Airport
--   * AIRBASE.Nevada.Jean_Airport
--   * AIRBASE.Nevada.Laughlin_Airport
--   * AIRBASE.Nevada.Lincoln_County
--   * AIRBASE.Nevada.Mesquite
--   * AIRBASE.Nevada.Mina_Airport_3Q0
--   * AIRBASE.Nevada.North_Las_Vegas
--   * AIRBASE.Nevada.Pahute_Mesa_Airstrip
--   * AIRBASE.Nevada.Tonopah_Airport
--   * AIRBASE.Nevada.Tonopah_Test_Range_Airfield
-- @field Nevada
AIRBASE.Nevada = {
    ["Creech_AFB"] = "Creech AFB",
    ["Groom_Lake_AFB"] = "Groom Lake AFB",
    ["McCarran_International_Airport"] = "McCarran International Airport",
    ["Nellis_AFB"] = "Nellis AFB",
    ["Beatty_Airport"] = "Beatty Airport",
    ["Boulder_City_Airport"] = "Boulder City Airport",
    ["Echo_Bay"] = "Echo Bay",
    ["Henderson_Executive_Airport"] = "Henderson Executive Airport",
    ["Jean_Airport"] = "Jean Airport",
    ["Laughlin_Airport"] = "Laughlin Airport",
    ["Lincoln_County"] = "Lincoln County",
    ["Mesquite"] = "Mesquite",
    ["Mina_Airport_3Q0"] = "Mina Airport 3Q0",
    ["North_Las_Vegas"] = "North Las Vegas",
    ["Pahute_Mesa_Airstrip"] = "Pahute Mesa Airstrip",
    ["Tonopah_Airport"] = "Tonopah Airport",
    ["Tonopah_Test_Range_Airfield"] = "Tonopah Test Range Airfield",
}

--- These are all airbases of Normandy:
--
--   * AIRBASE.Normandy.Saint_Pierre_du_Mont
--   * AIRBASE.Normandy.Lignerolles
--   * AIRBASE.Normandy.Cretteville
--   * AIRBASE.Normandy.Maupertus
--   * AIRBASE.Normandy.Brucheville
--   * AIRBASE.Normandy.Meautis
--   * AIRBASE.Normandy.Cricqueville_en_Bessin
--   * AIRBASE.Normandy.Lessay
--   * AIRBASE.Normandy.Sainte_Laurent_sur_Mer
--   * AIRBASE.Normandy.Biniville
--   * AIRBASE.Normandy.Cardonville
--   * AIRBASE.Normandy.Deux_Jumeaux
--   * AIRBASE.Normandy.Chippelle
--   * AIRBASE.Normandy.Beuzeville
--   * AIRBASE.Normandy.Azeville
--   * AIRBASE.Normandy.Picauville
--   * AIRBASE.Normandy.Le_Molay
--   * AIRBASE.Normandy.Longues_sur_Mer
--   * AIRBASE.Normandy.Carpiquet
--   * AIRBASE.Normandy.Bazenville
--   * AIRBASE.Normandy.Sainte_Croix_sur_Mer
--   * AIRBASE.Normandy.Beny_sur_Mer
--   * AIRBASE.Normandy.Rucqueville
--   * AIRBASE.Normandy.Sommervieu
--   * AIRBASE.Normandy.Lantheuil
--   * AIRBASE.Normandy.Evreux
--   * AIRBASE.Normandy.Chailey
--   * AIRBASE.Normandy.Needs_Oar_Point
--   * AIRBASE.Normandy.Funtington
--   * AIRBASE.Normandy.Tangmere
--   * AIRBASE.Normandy.Ford_AF
-- @field Normandy
AIRBASE.Normandy = {
    ["Saint_Pierre_du_Mont"] = "Saint Pierre du Mont",
    ["Lignerolles"] = "Lignerolles",
    ["Cretteville"] = "Cretteville",
    ["Maupertus"] = "Maupertus",
    ["Brucheville"] = "Brucheville",
    ["Meautis"] = "Meautis",
    ["Cricqueville_en_Bessin"] = "Cricqueville-en-Bessin",
    ["Lessay"] = "Lessay",
    ["Sainte_Laurent_sur_Mer"] = "Sainte-Laurent-sur-Mer",
    ["Biniville"] = "Biniville",
    ["Cardonville"] = "Cardonville",
    ["Deux_Jumeaux"] = "Deux Jumeaux",
    ["Chippelle"] = "Chippelle",
    ["Beuzeville"] = "Beuzeville",
    ["Azeville"] = "Azeville",
    ["Picauville"] = "Picauville",
    ["Le_Molay"] = "Le Molay",
    ["Longues_sur_Mer"] = "Longues-sur-Mer",
    ["Carpiquet"] = "Carpiquet",
    ["Bazenville"] = "Bazenville",
    ["Sainte_Croix_sur_Mer"] = "Sainte-Croix-sur-Mer",
    ["Beny_sur_Mer"] = "Beny-sur-Mer",
    ["Rucqueville"] = "Rucqueville",
    ["Sommervieu"] = "Sommervieu",
    ["Lantheuil"] = "Lantheuil",
    ["Evreux"] = "Evreux",
    ["Chailey"] = "Chailey",
    ["Needs_Oar_Point"] = "Needs Oar Point",
    ["Funtington"] = "Funtington",
    ["Tangmere"] = "Tangmere",
    ["Ford_AF"] = "Ford_AF",
    ["Goulet"] = "Goulet",
    ["Argentan"] = "Argentan",
    ["Vrigny"] = "Vrigny",
    ["Essay"] = "Essay",
    ["Hauterive"] = "Hauterive",
    ["Barville"] = "Barville",
    ["Conches"] = "Conches",
}

--- These are all airbases of the Persion Gulf Map:
--
-- * AIRBASE.PersianGulf.Abu_Dhabi_International_Airport
-- * AIRBASE.PersianGulf.Abu_Musa_Island_Airport
-- * AIRBASE.PersianGulf.Al-Bateen_Airport
-- * AIRBASE.PersianGulf.Al_Ain_International_Airport
-- * AIRBASE.PersianGulf.Al_Dhafra_AB
-- * AIRBASE.PersianGulf.Al_Maktoum_Intl
-- * AIRBASE.PersianGulf.Al_Minhad_AB
-- * AIRBASE.PersianGulf.Bandar_e_Jask_airfield
-- * AIRBASE.PersianGulf.Bandar_Abbas_Intl
-- * AIRBASE.PersianGulf.Bandar_Lengeh
-- * AIRBASE.PersianGulf.Dubai_Intl
-- * AIRBASE.PersianGulf.Fujairah_Intl
-- * AIRBASE.PersianGulf.Havadarya
-- * AIRBASE.PersianGulf.Jiroft_Airport
-- * AIRBASE.PersianGulf.Kerman_Airport
-- * AIRBASE.PersianGulf.Khasab
-- * AIRBASE.PersianGulf.Kish_International_Airport
-- * AIRBASE.PersianGulf.Lar_Airbase
-- * AIRBASE.PersianGulf.Lavan_Island_Airport
-- * AIRBASE.PersianGulf.Liwa_Airbase
-- * AIRBASE.PersianGulf.Qeshm_Island
-- * AIRBASE.PersianGulf.Ras_Al_Khaimah_International_Airport
-- * AIRBASE.PersianGulf.Sas_Al_Nakheel_Airport
-- * AIRBASE.PersianGulf.Sharjah_Intl
-- * AIRBASE.PersianGulf.Shiraz_International_Airport
-- * AIRBASE.PersianGulf.Sir_Abu_Nuayr
-- * AIRBASE.PersianGulf.Sirri_Island
-- * AIRBASE.PersianGulf.Tunb_Island_AFB
-- * AIRBASE.PersianGulf.Tunb_Kochak
-- @field PersianGulf
AIRBASE.PersianGulf = {
    ["Abu_Dhabi_International_Airport"] = "Abu Dhabi Intl",
    ["Abu_Musa_Island_Airport"] = "Abu Musa Island",
    ["Al_Ain_International_Airport"] = "Al Ain Intl",
    ["Al_Bateen_Airport"] = "Al-Bateen",
    ["Al_Dhafra_AB"] = "Al Dhafra AFB",
    ["Al_Maktoum_Intl"] = "Al Maktoum Intl",
    ["Al_Minhad_AB"] = "Al Minhad AFB",
    ["Bandar_Abbas_Intl"] = "Bandar Abbas Intl",
    ["Bandar_Lengeh"] = "Bandar Lengeh",
    ["Bandar_e_Jask_airfield"] = "Bandar-e-Jask",
    ["Dubai_Intl"] = "Dubai Intl",
    ["Fujairah_Intl"] = "Fujairah Intl",
    ["Havadarya"] = "Havadarya",
    ["Jiroft_Airport"] = "Jiroft",
    ["Kerman_Airport"] = "Kerman",
    ["Khasab"] = "Khasab",
    ["Kish_International_Airport"] = "Kish Intl",
    ["Lar_Airbase"] = "Lar",
    ["Lavan_Island_Airport"] = "Lavan Island",
    ["Liwa_Airbase"] = "Liwa AFB",
    ["Qeshm_Island"] = "Qeshm Island",
    ["Ras_Al_Khaimah"] = "Ras Al Khaimah Intl",
    ["Sas_Al_Nakheel_Airport"] = "Sas Al Nakheel",
    ["Sharjah_Intl"] = "Sharjah Intl",
    ["Shiraz_International_Airport"] = "Shiraz Intl",
    ["Sir_Abu_Nuayr"] = "Sir Abu Nuayr",
    ["Sirri_Island"] = "Sirri Island",
    ["Tunb_Island_AFB"] = "Tunb Island AFB",
    ["Tunb_Kochak"] = "Tunb Kochak",
}

--- These are all airbases of the The Channel Map:
--
-- * AIRBASE.TheChannel.Abbeville_Drucat
-- * AIRBASE.TheChannel.Merville_Calonne
-- * AIRBASE.TheChannel.Saint_Omer_Longuenesse
-- * AIRBASE.TheChannel.Dunkirk_Mardyck
-- * AIRBASE.TheChannel.Manston
-- * AIRBASE.TheChannel.Hawkinge
-- * AIRBASE.TheChannel.Lympne
-- * AIRBASE.TheChannel.Detling
-- * AIRBASE.TheChannel.High_Halden
--
-- @field TheChannel
AIRBASE.TheChannel = {
    ["Abbeville_Drucat"] = "Abbeville Drucat",
    ["Merville_Calonne"] = "Merville Calonne",
    ["Saint_Omer_Longuenesse"] = "Saint Omer Longuenesse",
    ["Dunkirk_Mardyck"] = "Dunkirk Mardyck",
    ["Manston"] = "Manston",
    ["Hawkinge"] = "Hawkinge",
    ["Lympne"] = "Lympne",
    ["Detling"] = "Detling",
    ["High_Halden"] = "High Halden",
}

--- Airbases of Syria
--
-- * AIRBASE.Syria.Kuweires
-- * AIRBASE.Syria.Marj_Ruhayyil
-- * AIRBASE.Syria.Kiryat_Shmona
-- * AIRBASE.Syria.Marj_as_Sultan_North
-- * AIRBASE.Syria.Eyn_Shemer
-- * AIRBASE.Syria.Incirlik
-- * AIRBASE.Syria.Damascus
-- * AIRBASE.Syria.Bassel_Al_Assad
-- * AIRBASE.Syria.Aleppo
-- * AIRBASE.Syria.Qabr_as_Sitt
-- * AIRBASE.Syria.Wujah_Al_Hajar
-- * AIRBASE.Syria.Al_Dumayr
-- * AIRBASE.Syria.Hatay
-- * AIRBASE.Syria.Haifa
-- * AIRBASE.Syria.Khalkhalah
-- * AIRBASE.Syria.Megiddo
-- * AIRBASE.Syria.Rayak
-- * AIRBASE.Syria.Mezzeh
-- * AIRBASE.Syria.King_Hussein_Air_College
-- * AIRBASE.Syria.Jirah
-- * AIRBASE.Syria.Taftanaz
-- * AIRBASE.Syria.Rene_Mouawad
-- * AIRBASE.Syria.Ramat_David
-- * AIRBASE.Syria.Minakh
-- * AIRBASE.Syria.Adana_Sakirpasa
-- * AIRBASE.Syria.Marj_as_Sultan_South
-- * AIRBASE.Syria.Hama
-- * AIRBASE.Syria.Al_Qusayr
-- * AIRBASE.Syria.Palmyra
-- * AIRBASE.Syria.Tabqa
-- * AIRBASE.Syria.Beirut_Rafic_Hariri
-- * AIRBASE.Syria.An_Nasiriyah
-- * AIRBASE.Syria.Abu_al_Duhur
--
-- @field Syria
AIRBASE.Syria={
    ["Kuweires"]="Kuweires",
    ["Marj_Ruhayyil"]="Marj Ruhayyil",
    ["Kiryat_Shmona"]="Kiryat Shmona",
    ["Marj_as_Sultan_North"]="Marj as Sultan North",
    ["Eyn_Shemer"]="Eyn Shemer",
    ["Incirlik"]="Incirlik",
    ["Damascus"]="Damascus",
    ["Bassel_Al_Assad"]="Bassel Al-Assad",
    ["Aleppo"]="Aleppo",
    ["Qabr_as_Sitt"]="Qabr as Sitt",
    ["Wujah_Al_Hajar"]="Wujah Al Hajar",
    ["Al_Dumayr"]="Al-Dumayr",
    ["Hatay"]="Hatay",
    ["Haifa"]="Haifa",
    ["Khalkhalah"]="Khalkhalah",
    ["Megiddo"]="Megiddo",
    ["Rayak"]="Rayak",
    ["Mezzeh"]="Mezzeh",
    ["King_Hussein_Air_College"]="King Hussein Air College",
    ["Jirah"]="Jirah",
    ["Taftanaz"]="Taftanaz",
    ["Rene_Mouawad"]="Rene Mouawad",
    ["Ramat_David"]="Ramat David",
    ["Minakh"]="Minakh",
    ["Adana_Sakirpasa"]="Adana Sakirpasa",
    ["Marj_as_Sultan_South"]="Marj as Sultan South",
    ["Hama"]="Hama",
    ["Al_Qusayr"]="Al Qusayr",
    ["Palmyra"]="Palmyra",
    ["Tabqa"]="Tabqa",
    ["Beirut_Rafic_Hariri"]="Beirut-Rafic Hariri",
    ["An_Nasiriyah"]="An Nasiriyah",
    ["Abu_al_Duhur"]="Abu al-Duhur",
}


--- AIRBASE.ParkingSpot ".Coordinate, ".TerminalID", ".TerminalType", ".TOAC", ".Free", ".TerminalID0", ".DistToRwy".
-- @type AIRBASE.ParkingSpot
-- @field Core.Point#COORDINATE Coordinate Coordinate of the parking spot.
-- @field #number TerminalID Terminal ID of the spot. Generally, this is not the same number as displayed in the mission editor.
-- @field #AIRBASE.TerminalType TerminalType Type of the spot, i.e. for which type of aircraft it can be used.
-- @field #boolean TOAC Takeoff or landing aircarft. I.e. this stop is occupied currently by an aircraft until it took of or until it landed.
-- @field #boolean Free This spot is currently free, i.e. there is no alive aircraft on it at the present moment.
-- @field #number TerminalID0 Unknown what this means. If you know, please tell us!
-- @field #number DistToRwy Distance to runway in meters. Currently bugged and giving the same number as the TerminalID.

--- Terminal Types of parking spots. See also https://wiki.hoggitworld.com/view/DCS_func_getParking
--
-- Supported types are:
--
-- * AIRBASE.TerminalType.Runway = 16: Valid spawn points on runway.
-- * AIRBASE.TerminalType.HelicopterOnly = 40: Special spots for Helicopers.
-- * AIRBASE.TerminalType.Shelter = 68: Hardened Air Shelter. Currently only on Caucaus map.
-- * AIRBASE.TerminalType.OpenMed = 72: Open/Shelter air airplane only.
-- * AIRBASE.TerminalType.OpenBig = 104: Open air spawn points. Generally larger but does not guarantee large aircraft are capable of spawning there.
-- * AIRBASE.TerminalType.OpenMedOrBig = 176: Combines OpenMed and OpenBig spots.
-- * AIRBASE.TerminalType.HelicopterUsable = 216: Combines HelicopterOnly, OpenMed and OpenBig.
-- * AIRBASE.TerminalType.FighterAircraft = 244: Combines Shelter. OpenMed and OpenBig spots. So effectively all spots usable by fixed wing aircraft.
--
-- @type AIRBASE.TerminalType
-- @field #number Runway 16: Valid spawn points on runway.
-- @field #number HelicopterOnly 40: Special spots for Helicopers.
-- @field #number Shelter 68: Hardened Air Shelter. Currently only on Caucaus map.
-- @field #number OpenMed 72: Open/Shelter air airplane only.
-- @field #number OpenBig 104: Open air spawn points. Generally larger but does not guarantee large aircraft are capable of spawning there.
-- @field #number OpenMedOrBig 176: Combines OpenMed and OpenBig spots.
-- @field #number HelicopterUsable 216: Combines HelicopterOnly, OpenMed and OpenBig.
-- @field #number FighterAircraft 244: Combines Shelter. OpenMed and OpenBig spots. So effectively all spots usable by fixed wing aircraft.
AIRBASE.TerminalType = {
    Runway=16,
    HelicopterOnly=40,
    Shelter=68,
    OpenMed=72,
    OpenBig=104,
    OpenMedOrBig=176,
    HelicopterUsable=216,
    FighterAircraft=244,
}

dofile('../settings/settings-syria.lua')
print(json.stringify(CoalitionSquadrons))


dofile('../settings/settings-persiangulf.lua')
print(json.stringify(CoalitionSquadrons))
