fox=FOX:New()
fox:SetExplosionDistance(50)
fox:SetExplosionDistanceBigMissiles(100)
fox:SetExplosionPower(.1)
--  fox:SetDebugOn()
fox:SetDefaultLaunchAlerts(false)
fox:SetDefaultLaunchMarks(false)
fox:SetDefaultMissileDestruction(true)
fox:SetDisableF10Menu(true)
fox:Start()